Fixed jsamp sign algorithm for Java 1.7
When running on Java 1.7, the SPLAT fails to start because of signature
of jsamp library:

java.lang.SecurityException: invalid SHA1 signature file digest